version: 2.1
jobs:
  # build with machine executor
  build:
    working_directory: ~/astminer
    # python parser PATH variable
    environment:
      pythonparser: /tmp/pythonparser
    docker:
      - image: circleci/python:3.8
    steps:
      - run: 
          name: Installing backend - pythonparser for GumTree
          command: |
                git clone https://github.com/JetBrains-Research/pythonparser
                pip3 install -r pythonparser/requirements.txt
                mv pythonparser/src/main/python/pythonparser_3.py /tmp/pythonparser
                chmod +x /tmp/pythonparser
      - checkout:
          path: ~/astminer
      - run: ./gradlew build --stacktrace

  # release
  release:
    machine:
      enabled: true
    working_directory: ~/astminer
    environment:
      GIT_BRANCH: << pipeline.git.branch >>
    steps:
      - checkout:
          path: ~/astminer
      - run: ./gradlew bintrayUpload "-PbranchName=$GIT_BRANCH"


  release-dev:
    machine:
      enabled: true
    working_directory: ~/astminer
    environment:
      CI_VERSION: << pipeline.number >>
      GIT_BRANCH: << pipeline.git.branch >>
    steps:
      - checkout:
          path: ~/astminer
      - run: ./gradlew bintrayUpload "-PciVersion=1.$CI_VERSION" "-PbranchName=$GIT_BRANCH"


workflows:
  version: 2

  # release with manual approval in CircleCI app
  deploy-library:
    jobs:
      - build
      - approve-release:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - release:
          requires:
            - approve-release
          filters:
            branches:
              only:
                - master
      - release-dev:
          requires:
            - build
          filters:
            branches:
              only:
                - master-dev
